### ISSUE TITLE
ExoPlayer does not playing when locale change from English to Arabic

### ISSUE THREAD

**Issue by gabes-dev** [yusufcakmak/ExoPlayerSample#22]
ExoPlayer is playing well in locale with English.
But it does not playing when locale changes from English to Arabic.
There is no feature for subtitle in my app.

It occurs an exception as follows:
```
E/ExoPlayerImplInternal: Source error.
                         com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:931)
                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                             at java.lang.Thread.run(Thread.java:762)
```

**Comment by soonsam123** [comment]
Check if [this](https://github.com/google/ExoPlayer/issues/585) helps.

**Comment by gabes-dev** [comment]
Thanks for your reply.
I checked it.
I am using ExoPlayer 2.8.1 version, and it already changed to String.format(Locale.US, xxx) in UrlTemplate.java.
